### ISSUE TITLE
关于torchcv的sfnet实现

### ISSUE THREAD

**Issue by stillwaterman** [lxtGH/SFSegNets#1]
您好，我看了一下torchcv的sfnet实现，感觉和论文上的网络结构图有些出入。
![image](https://user-images.githubusercontent.com/20119289/92718025-c7707700-f393-11ea-975b-909ed3717936.png)
文章中最后融合decoder各个层的feature maps的时候是应用了FAM，我看sfnet的代码实现中，fusion_list的实现是decoder各层feature maps先通过conv3x3_bn_relu，然后用二次线性插值加上torch.cat实现融合的，我感觉和论文的描述有点不同，也可能是我代码没理解透，我不知道您怎么看这个问题。

**Comment by lxtGH** [comment]
@stillwaterman 我们只是在ablation里面尝试了这种design，但是gain 不多，后面新的版本会重点强调下。

**Comment by stillwaterman** [comment]
也就是说把FAM加到最后的decoder融合阶段不如把FAM加到skip connection中的效果明显对吧。文章很好，持续关注 @lxtGH 😄

**Comment by lxtGH** [comment]
可以这么理解，主要是增益只有0.3mIoU 但是速度掉了4 fps，得不偿失。
