### ISSUE TITLE
The pre-training model Resnet18-deep-Inplane128.pth is pre-trained in which data set? ImageNet or Mapillatus？

### ISSUE THREAD

**Issue by GitHubLiaoYong** [lxtGH/SFSegNets#11]
Hello.
Thanks for publishing a great code. I want to ask a question: The uploaded pre-training model resnet18-deep-inplane128.pth is pre-trained in which dataset? ImageNet or Mapillary？Thank you!

**Comment by lxtGH** [comment]
Hi, resnet18-deep-inplane128.pth is backbone network which is trained on ImageNet under the same setting with mobilenetv2.
