### ISSUE TITLE
为什么这个代码复现精度要比论文低呢，，，还有代码可不可以可视化学到的流场啊，没看见这部分代码在哪里啊

### ISSUE THREAD

**Issue by swjtulinxi** [lxtGH/SFSegNets#13]

**Comment by lxtGH** [comment]
可视化代码在 https://github.com/lxtGH/SFSegNets/tree/master/utils/flow_lib。另这个repo 结果比paper高。

**Comment by swjtulinxi** [comment]
f = psp_out
        fpn_feature_list = [psp_out]
        out = []
        for i in reversed(range(len(conv_out) - 1)):
            conv_x = conv_out[i]
            conv_x = self.fpn_in[i](conv_x)  # lateral branch
            f = self.fpn_out_align[i]([conv_x, f])
            **f = conv_x + f**
            fpn_feature_list.append(self.fpn_out[i](f))
            out.append(f) 
请问为什么这里的f是累加ppm，layer3，2，1，的结果，而不是把self.fpn_out[i](f)的结果赋值给 f 呢，这样似乎不是和fpn和unet结构一致啊
