### ISSUE TITLE
请问怎么可视化流场呢，文件夹下提供了一些可视化函数。但是不知道怎么开始可视化啊，请问能不能大概说下

### ISSUE THREAD

**Issue by swjtulinxi** [lxtGH/SFSegNets#14]
![image](https://user-images.githubusercontent.com/50089266/103206353-a0d04f00-4936-11eb-9ef0-84006f7f0f3c.png)

**Comment by lxtGH** [comment]
简单讲就是预测出来的flow map 输入到https://github.com/lxtGH/SFSegNets/blob/19cd84a0c78a2fcbc36b59cd7df27f14fb5b75ad/utils/flow_lib/visualize.py#L46
这个函数里就行了。

**Comment by ahhLS** [comment]
请问您可视化出来了吗？
