### ISSUE TITLE
关于Cityscapes的num_classes

### ISSUE THREAD

**Issue by ahhLS** [lxtGH/SFSegNets#15]
请问Cityscapes_label.py中的license plate是否是多余的呢？加上这一类num_classes是19吗？

**Comment by lxtGH** [comment]
city的num_classes 一般是19，background的类别在训练时候被设置成了ignore（一般为255），训练和测试时都不考虑。

**Comment by ahhLS** [comment]
> city的num_classes 一般是19，background的类别在训练时候被设置成了ignore（一般为255），训练和测试时都不考虑。
OK，Thanks！
