### ISSUE TITLE
请问如何用自己训练的模型在特定数据集上进行测试呢？

### ISSUE THREAD

**Issue by ahhLS** [lxtGH/SFSegNets#16]

**Comment by lxtGH** [comment]
Please refer to this issue: https://github.com/lxtGH/DecoupleSegNets/issues/3

**Comment by ahhLS** [comment]
> Please refer to this issue: [lxtGH/DecoupleSegNets#3](https://github.com/lxtGH/DecoupleSegNets/issues/3)

Thanks!I have sloved this problem.
