### ISSUE TITLE
Singel GPU with 8 memory

### ISSUE THREAD

**Issue by Lufei-github** [lxtGH/SFSegNets#19]
Hi, your code trained with multi GPUs,  but I only have a single GPU with 8 memory.

So what should I set to run this code with my single GPU？

I saw torch.distributed.init_process_group(), torch.distributed.all_reduce(). I think this may interrupting my training with single GPU.

**Comment by Lufei-github** [comment]
![Uploading 2021-01-14 10-54-09屏幕截图.png…]()

**Comment by Lufei-github** [comment]
![error](https://user-images.githubusercontent.com/47933628/104538812-8ea12100-5657-11eb-811a-a72ff1cbf25f.png)

**Comment by Lufei-github** [comment]
Warning:  apex was installed without --cpp_ext.  Falling back to Python flatten and unflatten.

**Comment by Lufei-github** [comment]
![2021-01-14 11-49-08屏幕截图](https://user-images.githubusercontent.com/47933628/104542514-9fa16080-565e-11eb-9c00-dfe59c1d765f.png)

**Comment by Lufei-github** [comment]
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/cuda/Module.cpp:59
Traceback (most recent call last):
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dalei1607/anaconda3/envs/pytorch1.4/bin/python', '-u', 'train.py', '--local_rank=7', '--dataset', 'cityscapes', '--cv', '0', '--arch', 'network.sfnet_resnet.DeepR18_SF_deeply', '--class_uniform_pct', '0.5', '--class_uniform_tile', '1024', '--lr', '0.01', '--lr_schedule', 'poly', '--poly_exp', '1.0', '--repoly', '1.5', '--rescale', '1.0', '--syncbn', '--sgd', '--ohem', '--crop_size', '1024', '--scale_min', '0.5', '--scale_max', '2.0', '--color_aug', '0.25', '--gblur', '--max_epoch', '300', '--wt_bound', '1.0', '--bs_mult', '2', '--apex', '--exp', 'cityscapes_SFsegnet_res18', '--ckpt', './sfets/sfnet_res18_300e_128_inplanes/', '--tb_path', './sfets/sfnet_res18_300e_128_inplanes/']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Total world size:  8
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/cuda/Module.cpp line=59 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/cuda/Module.cpp:59

**Comment by Lufei-github** [comment]
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/dalei1607/anaconda3/envs/pytorch1.4/lib/python3.6/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/cuda/Module.cpp:59

**Comment by lxtGH** [comment]
Sorry this project did not support the single gpu training.
