### ISSUE TITLE
Could you please explain why the performance of SFNet didn't reach the result claimed in the paper ?

### ISSUE THREAD

**Issue by seekFire** [lxtGH/SFSegNets#2]
I found the [issue](https://github.com/donnyyou/torchcv/issues/162) which talked about this in repo **donnyyou/torchcv**

**Comment by lxtGH** [comment]
We will release new trained model which are better than our paper.

**Comment by seekFire** [comment]
@lxtGH I think the achievement of your work has great potential, I'm looking forward to it very much, Thanks for your reply!

**Comment by lxtGH** [comment]
The code and models have been released.

**Comment by seekFire** [comment]
@lxtGH Great job! Thanks for your reminding!
