### ISSUE TITLE
Res50/Res101 预训练权重文件

### ISSUE THREAD

**Issue by ahhLS** [lxtGH/SFSegNets#20]
您好!我把从下面网址下载的预训练权重文件load进去之后，显示层不匹配。请问我该怎么处理呢？您可以提供相应的预训练权重文件吗？

'resnet50': 'https://download.pytorch.org/models/resnet50-19c8e357.pth',
 'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth',

**Comment by lxtGH** [comment]
你好 请用我们提供的预训练model 权重

**Comment by ahhLS** [comment]
> 你好 请用我们提供的预训练model 权重
感谢您的回复！请问：
1.resnet18-deep-stem-pytorch 和 sf-resnet18-Mapillary这两个预训练的权重文件有什么区别呢？
2.我按照您说的采用dfv1训练，但是报错RuntimeError: The expanded size of the tensor (8192) must match the existing size (2097152) at non-singleton dimension 1.  Target sizes: [9, 8192].  Tensor sizes: [2097152]，请问是什么原因呢？我需要修改其他的吗？
3.您能否提供该网络匹配的Res50和Res101的预训练权重文件呢？

**Comment by wangm9766** [comment]
同求使用deep-stem的ResNet50和ResNet101的预训练模型
