### ISSUE TITLE
关于FAM代码和torchcv里面有些许不同，？？

### ISSUE THREAD

**Issue by swjtulinxi** [lxtGH/SFSegNets#21]
norm = torch.tensor([[[[out_w, out_h]]]]).type_as(input).to(input.device)
h = torch.linspace(-1.0, 1.0, out_h).view(-1, 1).repeat(1, out_w)
w = torch.linspace(-1.0, 1.0, out_w).repeat(out_h, 1)
grid = torch.cat((w.unsqueeze(2), h.unsqueeze(2)), 2)
grid = grid.repeat(n, 1, 1, 1).type_as(input).to(input.device)
grid = grid + flow.permute(0, 2, 3, 1) / norm

在torchcv中，能不能说明一下 啊
norm = torch.tensor([[[[out_w, out_h]]]]).type_as(input).to(input.device)
w = torch.linspace(-1.0, 1.0, out_h).view(-1, 1).repeat(1, out_w)
h = torch.linspace(-1.0, 1.0, out_w).repeat(out_h, 1)
grid = torch.cat((h.unsqueeze(2), w.unsqueeze(2)), 2)
grid = grid.repeat(n, 1, 1, 1).type_as(input).to(input.device)
grid = grid + flow.permute(0, 2, 3, 1) / norm

**Comment by lxtGH** [comment]
仔细看下 逻辑是一样的 都是flow warping的操作
