### ISSUE TITLE
DFv1作为backbone训练

### ISSUE THREAD

**Issue by ahhLS** [lxtGH/SFSegNets#24]
我在使用DFv1作为backbone进行训练时，报错显示如下:
https://github.com/ahhLS/picture/blob/main/1.png
断点调试到错误出现的地方，显示如下：
https://github.com/ahhLS/picture/blob/main/2.png
这里的x的是一个tuple，我理解的是x[0]是输入的一个tensor，但是x[0]的shape为[2,9,64,64]，与输入的gts尺寸不匹配。这里的main_out是对特征图进行了上采样，才使得x[0]与gts尺寸一致，从而顺利进行forward。请问这块代码能具体解释一下吗？我如何修改才能进行正确的forward呢？

**Comment by XiaoJiNu** [comment]
您好，我在训练的时候也出现这个问题，请问有解决吗

**Comment by lxtGH** [comment]
Adding fpn_dsn_loss opinion. 
Please check the latest version.
