### ISSUE TITLE
problem of training train_cityscapes_sfnet_dfv1.sh

### ISSUE THREAD

**Issue by XiaoJiNu** [lxtGH/SFSegNets#30]
Hi, when I trained trining train_cityscapes_sfnet_dfv1.sh, an error as fllows which is from b,c,h,w = pred.size() in loss.py:
'tuple object has no attribute size‘
I fond that pred contains 2 predicted tensors whose shape is 2x19x64x64 . Then, I use pred[0] as pred but other error come out as fllows:

 File "/media/ssd2/yr/CV/segmentation/SFSegNets/loss.py", line 272, in forward
    prob = prob.masked_fill_(~valid_mask, 1)
RuntimeError: The expanded size of the tensor (8192) must match the existing size (2097152) at non-singleton dimension 1.  Ta       rget sizes: [19, 8192].  Tensor sizes: [2097152]

What shold I do to train  train_cityscapes_sfnet_dfv1.sh correctly?

**Comment by lxtGH** [comment]
Adding fpn_dsn_loss opinion.
Please check the latest version.
