### ISSUE TITLE
直接打印模型结构和提供的训练好的参数对应不太一致？

### ISSUE THREAD

**Issue by hanjr92** [lxtGH/SFSegNets#32]
使用resnet-18
```
net = DeepR18_SF_deeply(19, None)
print(net)
```
可以看到在网络结构里面layer1中使用了downsample
但是我下载sf_r18_799_map_trained.pth输出参数名称发现，layer1 的参数中并不存在 downsample这一步运算，为什么这个结构在训练好的参数中并不存在。

**Comment by jinfagang** [comment]
`DeepR18_SF_deeply_dsn` this pretrained related pth provided? Where is it?

**Comment by lxtGH** [comment]
@hanjr92 给个截图看下？

**Comment by hanjr92** [comment]
![Uploading layer1-sfnet.jpg…]()
![Uploading sfnet-weights.jpg…]()

**Comment by hanjr92** [comment]
> `DeepR18_SF_deeply_dsn` this pretrained related pth provided? Where is it?
I use `DeepR18_SF_deeply` not ` DeepR18_SF_deeply_dsn`. Pretraind model_urls are listed in 'resnet_d.py'.

**Comment by hanjr92** [comment]
我发现问题了= =！应该使用sfnet_r18_map.pth参数就是和我打印的一致。
