### ISSUE TITLE
Demo still invalid, Please provide pretrained weigth 

### ISSUE THREAD

**Issue by jinfagang** [lxtGH/SFSegNets#33]
![image](https://user-images.githubusercontent.com/21303438/112834029-1086df00-90ca-11eb-9251-f69de374a7ae.png)

Please provide pretrained weights with this model: `network.sfnet_resnet.DeepR18_SF_deeply_dsn`

I tried both `network.sfnet_resnet.DeepR18_SF_deeply_dsn` and `network.sfnet_resnet.DeepR18_SF_deeply`, none of them work.

**Comment by lxtGH** [comment]
Hi! try this (https://drive.google.com/file/d/1-U6NzJ0vb3q4Ev7YZ5FkL9X0L__bozM2/view?usp=sharing)?

**Comment by jinfagang** [comment]
@lxtGH Please send public link, this link needs request approve.....

**Comment by jinfagang** [comment]
@lxtGH Please publish this link to README. Since you choose opensource your code, make it more reliable and reproducable.

**Comment by lxtGH** [comment]
This link is public link. I have add it into readme. For previous ckpt. can you give the figure of loading process? It seem like some paramters are not loaded.

**Comment by lxtGH** [comment]
OK I will update the model weights~

**Comment by china-gaozw** [comment]
Can you provide the “Baidu Netdisk" link of the pretrained models and trained CKPT files? Thans.
