### ISSUE TITLE
about align_corners in grid_sample

### ISSUE THREAD

**Issue by 0liliulei** [lxtGH/SFSegNets#34]
First thank you for making this promising work public !
I came across some problems while running the demo.

`UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.`

It seems like the version you recommend is pytorch>=1.2, which is not enough for me to deduce what value should be set here.

**Comment by lxtGH** [comment]
set align_corners=True for the final inference.
