### ISSUE TITLE
Unable to reproduce train

### ISSUE THREAD

**Issue by jinfagang** [lxtGH/SFSegNets#37]
Loss divergency in epoch 2... even I narrow down lr:

![image](https://user-images.githubusercontent.com/21303438/113999035-39f2f800-988c-11eb-8874-311445a6906c.png)

**Comment by jinfagang** [comment]
My pytorch version is 1.7 @lxtGH  Please not using `pytorch >=1.2` if you didn't test higher version.

At least on my side, pytorch 1.7 don't support a lot APIs in your old code.

**Comment by lxtGH** [comment]
It maybe the version problem. My enviroment is pt.1.3 and pt.1.4

**Comment by jinfagang** [comment]
@lxtGH Thanks for your reply. Would u help test on pytorch 1.7? It might be version issue but I don't where it is be. It can run, but doesn't make sense pytorch will break loss convergency.

**Comment by lxtGH** [comment]
Hi ! I will try to use pt1.4 and pt1.6 to run the code since pt1.7 is not supported by our server. I will update the results once I get the results. @jinfagang

**Comment by jinfagang** [comment]
@lxtGH Thanks. Once you done pls add more details about it such as model arch use, lr, GPUs etc. Better with loss curve

**Comment by lxtGH** [comment]
for pt1.4, pt1.6 I use the default setting in the cofing. The results are normal
