### ISSUE TITLE
FAM模块在反向传播的时候权重会更新吗

### ISSUE THREAD

**Issue by dd1ge** [lxtGH/SFSegNets#39]
你好同学，首先感谢你开源了这个仓库。
阅读你的代码发现，这里是通过FAM模块计算出两个特征图的流场，再以流场为grid，通过双线性插值将高层语义特征图上采样，请问我的理解是正确的吗？
如果是的话，那么在反向传播的过程中，会计算对于流场的导数吗？或者进一步说，在反向传播的过程中会更新FAM模块的参数吗？按照我浅陋的理解，感觉反向传播的时候对FAM模块的参数不会更新呀。
如果我理解有误，还望指点一二，谢谢同学！

**Comment by lxtGH** [comment]
你好！你的理解是对的。反向传播的过程中FAM的参数会更新，error通过双线性插值回传给产生flow的network。具体的细节可以看最原始的spatial transform network(NIPS2015)

**Comment by dd1ge** [comment]
嗯嗯，好的，感谢同学！！！

**Comment by dd1ge** [comment]
嗯嗯，好的，感谢同学！！！
