### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by chemanqiang** [lxtGH/SFSegNets#4]
您好！
        下载了您的训练模型，在使用eval，默认参数在1080下测试时，速度比较慢，DFnetv1只有9秒/帧，是我哪里设置不对吗？
        该如何处理可以达到您论文中描述的速度。谢谢！

**Comment by lxtGH** [comment]
DFnetv1 can run at least 70fps on 1080ti. 
You must have bugs in your code.
https://github.com/lxtGH/SFSegNets/blob/a79b7c845682fca39c6d08e121a51d4095ce7122/utils/misc.py#L310
Please refer this.

**Comment by chenjun2hao** [comment]
@lxtGH i have the same problem, the eval.py print:
`| 3/500 [00:24<1:01:09,  7.38s/it]`

with speed_test func, the result with 1070 is:
```python
FPS: 22.739590
Inference time 43.97616624832153 ms
```
i think the gap is mainly in multi-scale test plus flip test, etc. @chemanqiang
