### ISSUE TITLE
also question about fps

### ISSUE THREAD

**Issue by daixiaolei623** [lxtGH/SFSegNets#42]
@lxtGH 
Hi, thank you for your work, 
but when i run the demo_folder.py with sfnet_r18_78.pth to test the cityscapes image(1024x2048), i got the message that: ' inference takes 75.56 seconds, which takes 0.42 seconds per image, including saving results', i have one GTX 1080Ti. the 0.42 seconds per image is much longer than the 26 fps of the SFNet(ResNet-18) in your paper.
Could you please tell me what is the problem?
thank you.

**Comment by daixiaolei623** [comment]
@lxtGH 
Please help me，I really want to know what the problem is.
thank you.

**Comment by lxtGH** [comment]
The FPN DSN heads should not be included for inference. Also. SFnet with 26FPS is acceraleted with TensorRT.
