### ISSUE TITLE
there is not DeepR18_SF_deeply_map network

### ISSUE THREAD

**Issue by daixiaolei623** [lxtGH/SFSegNets#43]
@lxtGH 
hi,
i want to train the res18+map ,however, i only find the DeepR18_SF_deeply_dsn network in sfnet_resnet.py,
there is not DeepR18_SF_deeply_map.

**Comment by lxtGH** [comment]
https://drive.google.com/file/d/1Hq7HhszrAicAr2PnbNN880ijAYcxJJ0I/view
the map pretrained model can be found in this link. We do not provide the DeepR18_SF_deeply_map model. You can train it by yourself. We have provided the scripts for mapillary training.
