### ISSUE TITLE
Question about the flow_make and flow_warp functions.

### ISSUE THREAD

**Issue by wuwenbin970731** [lxtGH/SFSegNets#47]
Hi, thank you for your nice work.
But I have some questions about the flow_make and flow_warp functions.
In your code, you use a  Conv2d `self.flow_make = nn.Conv2d(outplane*2, 2, kernel_size=kernel_size, padding=1, bias=False)` to make flow. But the Conv2d operator cannot guarantee that the range of output Flow is reasonable. So even you use a norm operation, you can not get a reasonable grid in flow_wap.
Is this a problem?
Looking forward for your reply. Thanks.

**Comment by lxtGH** [comment]
The norm operation is done in warping code.
