### ISSUE TITLE
mIoU is lower than 79%

### ISSUE THREAD

**Issue by mosjoker** [lxtGH/SFSegNets#5]
Hello.
Thanks for publishing a great code.
I trained SFNet with default setting of scripts/train_cityscapes_sfnet_res18.sh.But i got only 73 mIoU.
Diff:
- Res18 pretrain model.(Model channels(64) does not match the model，so I don't load the pretrain model)
- CityScapes Dir name.(Such as img_dir_name = 'leftImg8bit_trainvaltest')
- Pytorch version. (Some default settings)

**Comment by mosjoker** [comment]
@lxtGH Some code in datasets/mapillary may be placed in a function.

**Comment by lxtGH** [comment]
Thanks for remind. I upload the correct pretrained models of r18. Please try again!

**Comment by lxtGH** [comment]
The pretrained model is very important for r18.

**Comment by mosjoker** [comment]
Thanks for your reply.  Closed.
