### ISSUE TITLE
C盘的占用率是100%

### ISSUE THREAD

**Issue by gaowq2017** [lxtGH/SFSegNets#52]
作者您好，感谢开源代码，在训练的时候C盘的占用率是100%，查看了我能想到的所有原因但是无解，在训练时有两个警告分别为：
1、运用了上采样upsample;
2、运用函数F.grid_sample；
想请教一下这种情况正常吗？或者有什么办法可以解决？谢谢！

**Comment by lxtGH** [comment]
你好 这种问题我没遇到过 这个代码没有在window上运行过。不能保证能否在window 运行。
