### ISSUE TITLE
The "FAM" is indeed a stripped-down version of "DCN"

### ISSUE THREAD

**Issue by heziliustc** [lxtGH/SFSegNets#53]
Please read this paper "Understanding Deformable Alignment in Video Super-Resolution" by Kelvin.
The "FAM" is indeed a stripped-down version of "DCN" when kenel_size=1, flow calculation and warp operations conduct the same as "DCN".

**Comment by lxtGH** [comment]
@heziliustc "The "FAM" is indeed a stripped-down version of "DCN" when kenel_size=1, flow calculation and warp operations conduct the same as "DCN." For implementation of flow warping , yes ,it is.  However, to generate semantic flow, it is necessary to take two features as inputs (low resolution with high semantics, high resoltion with low semantics).  Thus, it is different.

**Comment by lxtGH** [comment]
Moreover, Our work acctually is developed at 2019. 3-4. But it takes a long time to publish (3. 2020 on arxiv). "Understanding Deformable Alignment in Video Super-Resolution" by Prof.CCloy is half year behind.
