### ISSUE TITLE
pretrain for resnet18

### ISSUE THREAD

**Issue by jyang68sh** [lxtGH/SFSegNets#57]
Hi. Just curious that is your pretrain link in readme for resnet18 correct?

I tried to train your model in mmseg framework, and got 3%-5% lower miou with your pretrain than r18v1c pretrain. 

Any thoughts? Thanks!

BTW best I got with r18v1c pretrain is 76.8 miou
with your r18 pretrain it is 73.32 miou

**Comment by lxtGH** [comment]
I am not surely the performance on mmseg. But in this codebase, we use the my pretrained r18 using this codebae.
https://github.com/implus/PytorchInsight If I have a time I will reproduce SFNet using mmseg. However, I did not have enought time for this. I can use our codebase for research.
