### ISSUE TITLE
Train on less than 8 GPUs

### ISSUE THREAD

**Issue by BabaVegato** [lxtGH/SFSegNets#59]
Hello, thanks for your detailed work.
I'd like to train your SFNet, but I don't have 8 GPUs available simultaineously in my lab, rather 2, 3, let's say 4. I'm a beginner in Apex, so I don't know if I can tweak the code to train on less than 8. Is it possible ?

Thanks.

**Comment by lxtGH** [comment]
You can train our model with 4 GPUs which can also achieve simular results.

**Comment by hanur13** [comment]
Hi,
I'd like to train SFNet but I only have 1 GPU.
Where I should tweek the code If possible using only 1 GPU?
-Thanks-
