### ISSUE TITLE
which parameter controls the sampling?

### ISSUE THREAD

**Issue by YongjieYang-YY** [lxtGH/SFSegNets#7]
I use train_cityscapes_sfnet_res18.sh to get 78.5. Is this corresponse "resnet18(no-balanced-sample): 78.4 mIoU"?

and how can I get  "resnet18: 79.0 mIoU"?

**Comment by lxtGH** [comment]
class_uniform_pct contorl the sampling process. Use this scripts https://github.com/lxtGH/SFSegNets/blob/master/scripts/train_cityscapes_sfnet_res18.sh, by changing the epochs into 600. You can obtain the performance.

**Comment by YongjieYang-YY** [comment]
Thanks
