### ISSUE TITLE
SFNet-Lite DSN issue [Not using dsn in forward pass]

### ISSUE THREAD

**Issue by jnisarg** [lxtGH/SFSegNets#78]
In the UperNetAlignHeadV2, DSN is not used in the forward pass and only an empty list as the second output.

So, how are you considering deep supervision for ### _DeepR18_SFV2_deeply_dsn_FA_Atten_?

**Comment by lxtGH** [comment]
According to my experience, deep supervision is not that important when the training epoch is long enough.
