### ISSUE TITLE
Using my own model to execute the eval. Py file on the validation set MIoU is only 2 points over.

### ISSUE THREAD

**Issue by GitHubLiaoYong** [lxtGH/SFSegNets#8]
Hello.
Thanks for publishing a great code.
When I made multi-scale predictions(eval.py) using a model I had trained myself, MIoU was very low (2.5%), for unknown reasons. Using my own code(single scale prediction) for calculating MIoU, my model was able to achieve 75%MIoU on the validation set.
If you know the reason, please reply, thank you.

**Comment by GitHubLiaoYong** [comment]
When I set --single_scale in eval.py. The following error occurred:

**Comment by lxtGH** [comment]
It is strange. I did not such problems.

**Comment by GitHubLiaoYong** [comment]
Thank you for your reply. I have solved the problem.

**Comment by ahhLS** [comment]
> Thank you for your reply. I have solved the problem.
hi，I want to ask you some question,how can I contact you?
